---

- import_tasks: user.yml
  when: patroni_install_from_pip

- name: Install system packages for patroni
  package:
    name: "{{ patroni_system_packages | map(attribute='name') | list }}"
    state: present
    update_cache: yes
  when: patroni_install_from_pip

- import_tasks: postgresql.yml
  when: not patroni_postgresql_exists

- import_tasks: watchdog.yml
  when: patroni_watchdog_mode in ('automatic', 'required')

- name: Install pip packages for patroni
  pip:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    umask: "{{ item.umask }}"
    executable: "{{ item.executable }}"
  with_items:
    - "{{ patroni_pip_packages }}"
  when: patroni_install_from_pip
