---
- import_tasks: user.yml
  when: patroni_install_from_pip

- name: Ensure system packages are installed
  package:
    name: "{{ patroni_system_packages | map(attribute='name') | list }}"
  when: patroni_install_from_pip

- import_tasks: postgresql.yml
  when: not patroni_postgresql_exists

- name: Update postgresql client links
  ansible.builtin.command:
    cmd: "/opt/pgpro/std-{{ patroni_postgresql_version }}/bin/pg-wrapper links update"
  when: ansible_os_family in ('Debian', 'Astra Linux')

- import_tasks: watchdog.yml
  when: patroni_watchdog_mode in ('automatic', 'required')

- name: Ensure pip packages installed for Patroni
  pip:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    umask: "{{ item.umask }}"
    executable: "{{ item.executable }}"
  with_items:
    - "{{ patroni_pip_packages }}"
  when: patroni_install_from_pip
