---
- name: Add patroni group
  ansible.builtin.group:
    name: "{{ patroni_system_group }}"
    state: present

- name: Add patroni user
  ansible.builtin.user:
    name: "{{ patroni_system_user }}"
    group: "{{ patroni_system_group }}"
    system: yes
