---
- name: Ensure patroni-watchdog is restarted
  systemd:
    name: patroni-watchdog
    state: restarted
    daemon_reload: yes
    enabled: yes
  notify:
    - restart watchdog

- name: Ensure watchdog is restarted
  systemd:
    name: watchdog
    state: restarted
    enabled: yes

- name: Ensure patroni is restarted
  systemd:
    name: patroni.service
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: Ensure haproxy is restarted
  systemd:
    name: haproxy.service
    state: restarted
    daemon_reload: yes
    enabled: yes
